# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
repository: royxinxin/xinying.github.io
quotes: 新新的学习笔记
title: 新新
name: 新新
email: 2602250460@qq.com
location: China
company: 无
#company_url: http://www.gfi.fr/en/
github_url: https://github.com/royxinxin
description: 本站是新新的学习笔记分享占
keywords: 本站是新新的学习笔记分享占
favicon: favicon.png # Image must be in assets/images

url: https://royxinxin.github.io # the base hostname & protocol for your site

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata



# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []
kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: 首页

  -
    href: /open-source
    label: 开源

  -
    href: /blog
    label: 博客

  -
    href: /bookmark
    label: 书签

  -
    href: /about
    label: 关于
  -
    href: /system_structure
    lable: 操作系统

class:
  -
    name: 自考计算机科学与技术
    href: /this_test
  -
    name: Python
    href: /Python
  -
    name: 博客
    href: /my_blog_index  
  -
    name: 区块链
    href: /block_chain

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-72165600-1'

skkil:
  -
    name: 游戏
    skills: [貂蝉三杀, 小明上过铜标, 孙尚香三杀, 王者贼溜, 开心消消乐则厉害,]
  -
    name: 优点
    skills: [沟通能力不错, 有爱心]
  -
    name: 缺点
    skills: []

